In [1]:
import tensorflow as tf

In [2]:
#CREATING TENSORS
#tensor - each tensor represents a partially defined computation that will eventually produce a value. 
#creating tensors of different datatypes:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

#these tensors have a shape of 1. It is a scalar value. 

In [4]:
#RANK/DEGREE OF TENSORS
#Another word for rank is degree, simply meaning the number of dimensions involved in the tensor.
#The tensors above are of rank 0, also known as a scalar. 
rank1_tensor = tf.Variable(["Test"], tf.string)
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)

#here we have a list, and array. The list has 1 dimensions, the array has 2 dimensions. 
#determine the degree / rank: how deep is a list nested?

tf.rank(rank2_tensor) #<tf.Tensor: shape=(), dtype=int32, numpy=2>

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [5]:
#SHAPE OF TENSORS
#shape of a tensor is the amount of elements that exist in each dimesnsion, or the size of the array. Sometimes it may be unknown. 
rank2_tensor.shape #TensorShape([2, 2])

TensorShape([2, 2])

In [8]:
#CHANGING SHAPE
#you can take a rank 2 tensor with 4 elements and turn it into a rank 1 tensor with 4 elements by making a single list. 

tensor1 = tf.ones([1,2,3]) #tf.ones() creates a shape [1,2,3] tensor full of ones.
print(tensor1) #(1-interior list, 2-lists inside that list, 3-elements in the list) -> 6 elements
#[[[1. 1. 1.]
#  [1. 1. 1.]]]
tensor2 = tf.reshape(tensor1, [2,3,1]) #reshape existing data to shape [2,3,1]
print(tensor2) #(2-interior lists, 3-lists inside those lists, 1-element in each list) -> 6 elements 
#[[[1.]
#  [1.]
#  [1.]]
# [[1.]
#  [1.]
#  [1.]]]
tensor3 = tf.reshape(tensor2, [3,-1])  #-1 tells the tensor to calculate the size of the dimension in that place
                                       # this will reshape the tense to [3,2]
print(tensor3) #(3- lists, 2-elements in each list) -> 6 elements                       
#[[1. 1.]
# [1. 1.]
# [1. 1.]]


#the number of elements in the reshaped tensor MUST match the number in the original. 

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [ ]:
#TYPES OF TENSORS
# - Variables
# - Constant
# - Placeholder 
# - SparseTensor

#with the exception of variable, all of these tensors are immuttable, meaning their value may not change during execution. 

In [ ]:
#EVALUATION TENSORS
#There will be some times when we need to get a tensors value. Since tensors represent a partially complete computation we will sometimes need to run what's called a session to evaluate the tensor. 

with tf.Session() as sess: #create a session using the default graph
    tensor.eval() #tensor will be the name of your tensor

In [11]:
#RESHAPING EXAMPLES
t = tf.zeros([5,5,5,5])
print(t)
t_flat = tf.reshape([625, -1],t_flat)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0.